-- Daily reminder push notifications.
-- Flow: pg_cron (every 5 min) -> Edge Function "send-reminders" -> due_reminders()
-- -> Web Push to each of the user's subscribed devices.

create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;

alter table public.user_settings
  add column reminder_time time not null default '20:00',
  add column last_reminded_on date;

-- One row per device (browser / installed app) with reminders turned on.
create table public.push_subscriptions (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  primary key (user_id, endpoint)
);

alter table public.push_subscriptions enable row level security;

create policy "own push subscriptions" on public.push_subscriptions
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- Shared secret the cron job sends to the Edge Function (never leaves the DB).
select vault.create_secret(
  encode(extensions.gen_random_bytes(32), 'hex'),
  'reminder_cron_secret',
  'Authenticates pg_cron calls to the send-reminders Edge Function'
);

-- ---------------------------------------------------------------------------
-- Service-role-only helpers used by the Edge Function
-- ---------------------------------------------------------------------------

create function public.push_config()
returns table (vapid_public text, vapid_private text, cron_secret text)
language sql
stable
security definer
set search_path = ''
as $$
  select
    (select decrypted_secret from vault.decrypted_secrets where name = 'vapid_public_key'),
    (select decrypted_secret from vault.decrypted_secrets where name = 'vapid_private_key'),
    (select decrypted_secret from vault.decrypted_secrets where name = 'reminder_cron_secret')
$$;

-- Stores VAPID keys generated by the Edge Function on first run (no-op if set).
create function public.set_vapid_keys(p_public text, p_private text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from vault.secrets where name = 'vapid_public_key') then
    perform vault.create_secret(p_public, 'vapid_public_key', 'Web Push VAPID public key');
    perform vault.create_secret(p_private, 'vapid_private_key', 'Web Push VAPID private key');
  end if;
end;
$$;

-- Users whose reminder time has passed (within the last 2 hours) in their own
-- timezone, who haven't been reminded today and have at least one device.
create function public.due_reminders()
returns table (
  user_id uuid,
  local_day date,
  remaining text[],
  active_goal_min int,
  passive_goal_min int
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    s.user_id,
    l.local_day,
    array(
      select k from unnest(array['anki', 'active', 'passive']) as k
      where not exists (
        select 1 from public.daily_tasks t
        where t.user_id = s.user_id and t.day = l.local_day and t.kind = k
      )
    ),
    s.active_goal_min,
    s.passive_goal_min
  from public.user_settings s
  cross join lateral (
    select
      (now() at time zone s.timezone)::date as local_day,
      (now() at time zone s.timezone)::time as local_time
  ) l
  where l.local_time - s.reminder_time >= interval '0'
    and l.local_time - s.reminder_time < interval '2 hours'
    and (s.last_reminded_on is null or s.last_reminded_on < l.local_day)
    and exists (select 1 from public.push_subscriptions p where p.user_id = s.user_id)
$$;

revoke execute on function public.push_config() from public, anon, authenticated;
revoke execute on function public.set_vapid_keys(text, text) from public, anon, authenticated;
revoke execute on function public.due_reminders() from public, anon, authenticated;
grant execute on function public.push_config() to service_role;
grant execute on function public.set_vapid_keys(text, text) to service_role;
grant execute on function public.due_reminders() to service_role;

-- The browser needs the public key to subscribe; it's safe to share.
create function public.get_vapid_public_key()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select decrypted_secret from vault.decrypted_secrets where name = 'vapid_public_key'
$$;

revoke execute on function public.get_vapid_public_key() from public, anon;
grant execute on function public.get_vapid_public_key() to authenticated;
